### PR TITLE
WIP: Simplify conda build process

### PR DESCRIPTION
**Pull request by mcg1969**

### CODE REVIEW

**Comment by mcg1969** [comment]
Let's not be in a hurry to merge this—there is a fair amount of choreography that has to happen to get this to start passing on Windows. I'll detail this in my PR for osqp-python once I'm happy with the result here.

**Comment by bstellato** [comment]
Sounds good! I totally understand it can take some time. CI can be incredibly annoying. Let me know if there anything I can do to help.

**Comment by mcg1969** [comment]
@bstellato: if you take a look at the amount of simplification this affords, it strikes me that it may not be all that helpful to have the `ci/` scripts directory anymore, in favor of inlining the (greatly reduced) scripts directly into `appveyor.yml` and `.travis.yml`. What do you think?

**Comment by mcg1969** [comment]
Also: what is your thinking around putting the recipe in `conda_recipe/osqp/`, two levels deep? I don't think you lose anything by calling it just `osqp/` or `conda-recipe/`, but you may have something else in mind.

**Comment by bstellato** [comment]
I am totally in favor of simplifying things. If we could inlinine everything into the appveyor and travis yml files I would be happy. Also, eliminating all the subfolders and having only `conda-recipe/` would be a good simplifcation. When I created the two-level subfolder I though about other possible recipes to create along with osqp but in the end we never needed them.

**Comment by mcg1969** [comment]
OK! The Appveyor script has been fully reduced. Travis next.

**Comment by mcg1969** [comment]
@bstellato as you can see, commit [`c36146e`](
https://github.com/oxfordcontrol/osqp-recipes/pull/1/commits/c36146e41647fd8a6730910ad215309484d12ed6) passes. But that commit was pointing to [my tagged release `v0.4.0-conda`](https://github.com/mcg1969/osqp-python/tree/v0.4.0-conda) with the necessary changes made to `setup.py` to get everything working. Now I've pointed it back to your repository, and to a tagged version of 0.4.1 without those fixes, and it's failing again.

So this is the order of things you need to do:
- Merge https://github.com/oxfordcontrol/osqp-python/pull/6/files
- Whenever you are ready, tag release 0.4.1. You could do it immediately, and push off your current changes to 0.4.2, or do it now.
- Merge this PR.

**Comment by bstellato** [comment]
I have merged. It builds the recipes successfully. However the deploy now seems broken on master.

**Comment by mcg1969** [comment]
I’m not at my desk right now. What’s the symptoms?

**Comment by mcg1969** [comment]
(When I do get to my desk, I should be able to look at the build log and see for myself)

**Comment by bstellato** [comment]
Error 127. Probably it is related to travis not finding some executable or some permission errors on the executables called from the deploy script. I am not in front of my computer now but I could check tomorrow. 

Thanks for the help!

**Comment by mcg1969** [comment]
https://github.com/travis-ci/travis-ci/issues/5538

**Comment by bstellato** [comment]
I think I solved it. We had 2 commands specified in the `.travis.yml` file in the custom script deployment. From [travis documentation](https://docs.travis-ci.com/user/deployment/script/) you cannot have multiple commands within the custom script without creating a separate bash file to run. To solve that I just merged the two commands in a single command with a semicolon.

**Comment by mcg1969** [comment]
Ah, that's interesting. Another approach is just to include the `anaconda-client` installation into the build section. Even though we only need that package for deployment, it simplifies things. Then the only thing that is left in the deployment section is the `anaconda upload`.

**Pull request merged**
